CREATE TABLE `devschema`.`pious_student` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ROLL_NO` INT NOT NULL,
  `DEPT` VARCHAR(45) NOT NULL,
  `NSS` TINYINT NULL,
  `NCC` TINYINT NULL,
  `SCHOLRSHIP` TINYINT NULL,
  `SPORTS` TINYINT NULL,
  PRIMARY KEY (`ID`));
  